global:
  domain: argocd.argocd.svc.cluster.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP

controller:
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

repoServer:
  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
