redis:
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi"

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false

global:
  domain: argocd.argocd.svc.cluster.local

configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"

controller:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"

repoServer:
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "768Mi"
