controller:
  serviceType: ClusterIP
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - credentials-binding
    - configuration-as-code
    - job-dsl
    - github
  installLatestPlugins: false
  numExecutors: 0
  executorMode: NORMAL
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  persistence:
    enabled: true
    size: 8Gi
  JCasC:
    defaultConfig: true

agent:
  enabled: true
  alwaysPullImage: true
  idleMinutes: 5
  podName: "jenkins-agent"

rbac:
  create: true

serviceAccount:
  create: true
